#!/bin/sh
path=$(pwd)

ln -sf $path/.zshrc $HOME/.zshrc
ln -sf $path/.zshenv $HOME/.zshenv

[ ! -d $HOME/.config ] && mkdir $HOME/.config

[ -d $HOME/.zsh ] && rm -rf $HOME/.zsh
mkdir $HOME/.zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.zsh/zsh-autosuggestions
git clone https://github.com/lukechilds/zsh-nvm.git $HOME/.zsh/zsh-nvm

[ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
ln -sf $path/config/nvim $HOME/.config/nvim
