#!/bin/sh
path=$(pwd)

ln -sf $path/.zshrc $HOME/.zshrc
ln -sf $path/.zshenv $HOME/.zshenv
ln -sf $path/.xinitrc $HOME/.xinitrc

[ ! -d $HOME/.config ] && mkdir $HOME/.config

[ -d $HOME/.zsh ] && rm -rf $HOME/.zsh
mkdir $HOME/.zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.zsh/zsh-autosuggestions
git clone https://github.com/lukechilds/zsh-nvm.git $HOME/.zsh/zsh-nvm
git clone https://github.com/zsh-users/zsh-completions.git $HOME/.zsh/zsh-completions

[ ! -d $HOME/.config/VSCodium ] && mkdir -p $HOME/.config/VSCodium/User
[ ! -d $HOME/.config/VSCodium/User ] && mkdir $HOME/.config/VSCodium/User
ln -sf $path/config/VSCodium/settings.json $HOME/.config/VSCodium/User/settings.json

[ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
ln -sf $path/config/nvim $HOME/.config/nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

[ -d $HOME/.local/share/fonts ] && rm -r $HOME/.local/share/fonts
ln -sf $path/.local/share/fonts $HOME/.local/share/fonts

ln -sf $path/config/wall.png $HOME/.config/wall.png
